{
	"version": 1725541179,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/camera-sheet0.png",
		"images/player-sheet0.png",
		"images/spikes-sheet0.png",
		"images/enemy_1-sheet0.png",
		"images/enemy_1-sheet1.png",
		"images/gameoverbackground-sheet0.png",
		"images/particles.png",
		"images/sprite-sheet0.png",
		"images/tilemap.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/enemy_2-sheet0.png",
		"images/enemy_2-sheet1.png",
		"images/enemy_3-sheet0.png",
		"images/bombe-sheet0.png",
		"images/coin-sheet0.png",
		"images/tilemap2.png",
		"images/tiledbackground4.png",
		"images/sprite2-sheet0.png",
		"images/boss-sheet0.png",
		"images/boss-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/healthbarsprite-sheet0.png",
		"images/heathbarspritebbackgroud-sheet0.png",
		"images/healthbarbg-sheet0.png",
		"images/healthbarfg-sheet0.png",
		"media/8bit-blip1.m4a",
		"media/8bit-blip1.ogg",
		"media/track 10 high lord wolnir.m4a",
		"media/track 10 high lord wolnir.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}